import type { Metadata } from "next";
import LandingNavbar from "../components/UI/LandingNavbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <LandingNavbar />
            {children}
        </>
    );
}
