import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/UI/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                <section className="pt-9">{children}</section>
            </body>
        </html>
    );
}
